### ISSUE TITLE
【新指令】挑逗小律影

### ISSUE THREAD

**Issue by Yanstory** [BAKAOLC/RitsukageBotRecord#3]
~挑逗小律影
挑逗一次小律影，小律影返回一个心情。
并**概率**根据心情返回下列情况之一：
- 生气：返回无视指令开关状态的雷击（无权限改为扣除幻币或一段时间内禁止挑逗）
- 不开心：扣除（极）少量幻币
- 一般般：无事发生
- 开心：赠送一点点幻币
- 非常开心：赠送数量略多的幻币，或豁免下次的掉钱事件雷击等等……

（是不是太迟了.jpg）

**Comment by TarringFox** [comment]
想要实装.jpg

**Comment by BAKAOLC** [comment]
但是并不会做.jpg
