### ISSUE TITLE
比如...整点报时？

### ISSUE THREAD

**Issue by TarringFox** [BAKAOLC/RitsukageBotRecord#7]
如果一天二十四小时每个整点都报时可能有点多的话，两个小时一次或者三个小时一次？群里可设置是否开启整点报时
（ps：如果小律影可以卖个萌就更好了）

**Comment by BAKAOLC** [comment]
报时我打算整个图，但是我并没有图可以发

**Comment by BAKAOLC** [comment]
完事了
